FROM postgres:15

COPY ./conf.sql /docker-entrypoint-initdb.d/
COPY ./init.sql /docker-entrypoint-initdb.d/

RUN chmod a+r /docker-entrypoint-initdb.d/conf.sql
RUN chmod a+r /docker-entrypoint-initdb.d/init.sql